# -*- coding: utf-8 -*-
"""Rock-Paper-Scissors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XuLSVCnu9JPTB54t4vi2idJfYRgjOHuv
"""

import random

options = ["rock","paper","scissors"]
u=0
c=0

while(True):
  user = input("Enter rock/paper/scissors or q to quit:").lower()
  if user == "q":
    print("You won {} times and computer won {} times".format(u,c))
    break
  elif user not in options:
    print("Please enter a valid choice")
  else:
    computer = options[random.randint(0,2)]
    print("The computer picked {}".format(computer))
    if user=="rock" and computer=="scissors":
      print("Hurray!! You won")
      u+=1
    elif user=="rock" and computer=="paper":
      print("Oops!! You lost")
      c+=1
    elif user=="paper" and computer=="rock":
      print("Hurray!! You won")
      u+=1
    elif user=="paper" and computer=="scissors":
      print("Oops!! You lost")
      c+=1
    elif user=="scissors" and computer=="paper":
      print("Hurray!! You won")
      u+=1
    elif user=="scissors" and computer=="rock":
      print("Oops!! You lost")
      c+=1
    else:
      print("Its a Tie!!!")